---
# File: roles/docker/tasks/main.yml
# Desc: installs and configures docker

- name: Include docker-daemon
  include_tasks: docker-daemon.yml
  when: docker_install_daemon | bool

- name: Include docker-compose
  include_tasks: docker-compose.yml
  when: docker_install_compose | bool

- name: Include docker-users
  include_tasks: docker-users.yml
  when: docker_users | length > 0

- name: Ensure handlers are notified now to avoid conflicts.
  meta: flush_handlers

