---

- name: Install dependencies
  apt:
    pkg:
      - openresolv
    state: present
    update_cache: yes

- name: Install WireGuard
  apt:
    name: wireguard
    state: present
    update_cache: yes

