---
# file: roles/docker/tasks/docker-compose.yml
# desc: Installs and configures docker-compose

- name: Install Docker dependencies
  apt:
    name: [ 'python3-pip']
    state: present
    update_cache: yes

- include_tasks: docker-compose-version.yml
  when: docker_compose_versioncheck | bool

- name: Check current docker-compose version.
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: Delete existing docker-compose version if it's different.
  file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and docker_compose_version not in docker_compose_current_version.stdout

- name: Install Docker Compose (if configured).
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ docker_compose_path }}"
    mode: 0755

- name: Install setuptools pip module
  pip:
    name: setuptools
    state: present

- name: Install docker-compose pip module
  pip:
    name: docker-compose
    state: present
