---
# file: roles/docker/tasks/docker-compose-version.yml
# desc: Checks for correct docker-compose version

- name: Docker Compose version check
  uri:
    url: https://www.servercow.de/docker-compose/latest.php
    return_content: yes
  register: uri_output

- name: Update facts
  set_fact:
    docker_compose_version: "{{ uri_output.stdout }}"
  when: >
    uri_output.content | length > 0
    and docker_compose_version not in uri_output.content
