---
# File: roles/docker/tasks/docker-daemon.yml
# Desc: installs and configures docker

- name: Install Docker dependencies
  apt:
    name: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']
    state: present
    update_cache: yes

- name: Add Docker's official GPG key
  apt_key:
    keyserver: https://download.docker.com/linux/ubuntu/gpg
    id: 0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: "{{ docker_apt_ignore_key_error }}"

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
  tags: docker

- name: Ensure daemon dir exists
  file:
    path: "{{ docker_daemon_dir }}"
    state: directory
  when: docker_daemon_opts | length > 0

- name: Add daemon options
  template:
    src: daemon.json.j2
    dest: "{{ docker_daemon_dir }}/daemon.json"
  when: docker_daemon_opts | length > 0
  notify: restart docker

