---
# File: roles/msmtp/tasks/msmtp.yml
# Desc: installs and configures msmtp

- name: Ensure packages are installed
  apt:
    name: "{{ msmtp_packages }}"
    state: present
    update_cache: yes
  notify: test mail
  when: ansible_os_family == "Debian"

- name: Copy mstprc conf file
  template:
     src=msmtprc.j2
     dest=/etc/msmtprc
     owner=root
     group=root
     mode=0644
  tags: mail
  notify: test mail

- name: Copy aliases conf file
  template:
      src=aliases.j2
      dest=/etc/aliases
      owner=root
      group=root
      mode=0644
  tags: mail
  notify: test mail
