---
# tasks file for ddclient

- name: Add the OS specific varibles
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Install the ddclient packages
  ansible.builtin.apt:
    name: "{{ ddclient_pkg }}"
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install the ddclient dependencies
  ansible.builtin.apt:
    name: ["libio-socket-ssl-perl"]
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Set ddclient config
  ansible.builtin.template:
    src: ddclient.conf.j2
    dest: "{{ ddclient_app_path }}/ddclient.conf"
    owner: root
    group: root
    # Contains the dynamic DNS password in plain text
    mode: "0600"
  when: ansible_os_family == "Debian"
  notify:
    - Restart ddclient
