---
# File: roles/base/tasks/sshd-config.yml
# Desc: Configures, tests and starts sshd

- name: configure sshd
  template:
    src: sshd_config.j2
    dest: "{{ sshd_config_basedir }}/sshd_config"
    owner: root
    group: root
    mode: "0400"
    validate: "/usr/sbin/sshd -t -f %s"
  notify: restart sshd
  tags: configuration

- name: enable sshd
  service:
    name: "{{ sshd_service_name }}"
    state: started
    enabled: yes
  tags: service

