---
# File: roles/base/tasks/se-packages.yml
# Desc: Installs packages and services. Enables services. Removes specific packages.

- name: Ensure packages are installed
  apt:
    name: "{{ base_packages }}"
    state: present
    update_cache: yes

- name: Extra packages to install
  apt:
    name: "{{ base_extra }}"
    state: present
    update_cache: yes
  when: base_extra is defined

- name: Ensure services are running and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ base_services }}"

- name: Ensure packages are removed
  apt:
    name: "{{ base_packages_removed }}"
    state: absent

