---
# File: roles/base/tasks/se-packages.yml
# Desc: Installs packages and services. Enables services. Removes specific packages.

- name: Ensure packages are installed
  ansible.builtin.apt:
    name: "{{ base_packages }}"
    state: present
    update_cache: true

- name: Extra packages to install
  ansible.builtin.apt:
    name: "{{ base_extra }}"
    state: present
    update_cache: true
  when: base_extra is defined

- name: Ensure services are running and enabled
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ base_services }}"

- name: Ensure packages are removed
  ansible.builtin.apt:
    name: "{{ base_packages_removed }}"
    state: absent
  when: base_packages_removed is defined
