---
- name: Build filename of file to be downloaded
  ansible.builtin.set_fact:
    cloudflared_file: "{{ vars['cloudflared_' + device_arch + '_' + ansible_pkg_mgr] }}"

- name: Download correct file for device
  ansible.builtin.get_url:
    url: "{{ cloudflared_base_url }}{{ cloudflared_file }}"
    dest: "/tmp/{{ cloudflared_file }}"
    mode: "0644"

- name: Install a .deb package
  ansible.builtin.apt:
    deb: "/tmp/{{ cloudflared_file }}"
    state: present
  register: pkg_mgr_output
  ignore_errors: true
  when: ansible_pkg_mgr == 'apt'

- name: Install a .rpm package
  ansible.builtin.dnf:
    name: "/tmp/{{ cloudflared_file }}"
    state: present
  register: pkg_mgr_output
  ignore_errors: true
  when: ansible_pkg_mgr == 'yum'
