---
- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart network
  service:
    name: networking
    state: restarted

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: reload fail2ban
  service:
    name: fail2ban
    state: reloaded

- name: reload systemd
  systemd_service:
    daemon_reload: true
